**Sentry错误分析和过滤**

## **处理rrweb插件捕获错误的流程**

先判断对应的错误信息是否含有堆栈信息，如果有堆栈信息，那么遍历堆栈信息（一个录制json可能存在多个exceptionFrames），使用source-map根据map文件、行号、列号进行还原，得到原代码的行列号、文件路径、具体代码等信息，然后通过Gitlab的api 根据文件路径、行列号来获取提交信息，定位出错代码开发者。然后把回放页面、出错路径、出错位置、出错代码、提交者信息在KIM中进行通知。

**如果可以获取对应行数代码的提交者，则返回提交者和最近一次文件的提交者**

**如果对应行数的代码提交者已经离职，则返回最近一次文件的提交者**

需要过滤的错误类型

npm包内部的错误：例如axios这种过滤不通知

没有堆栈信息的错误：不通知

错误文件路径不支持的：不通知

有堆栈信息但是没有对应文件路径的

## rrweb

**sentry学习**

sentry扮演着一个错误收集的角色，将你的项目和sentry结合起来，无论谁在项目使用中报错，sentry都会第一次时间通知开发者，我们需要在系统异常时主动对其进行收集上报，出现了什么错误，错误出现在哪，帮你记录错误，以制定解决方案并进行优化迭代。

### **什么是DSN**

DSN是连接客户端(项目)与sentry服务端,让两者能够通信的钥匙；每当我们在sentry服务端创建一个新的项目，都会得到一个独一无二的DSN，也就是密钥。在客户端初始化时会用到这个密钥，这样客户端报错，服务端就能抓到你对应项目的错误了。之前版本的sentry对于密钥分为公钥和私钥，一般前端用公钥(DSN(Public))，但是现在的版本舍弃了这种概念，只提供了一个密钥。

### **什么是event**

每当项目产生一个错误，sentry服务端日志就会产生一个event，记录此次报错的具体信息。一个错误，对应一个event。

### **什么是issue**

同一类event的集合，一个错误可能会重复产生多次，sentry服务端会将这些错误聚集在一起，那么这个集合就是一个issue。

### **什么是Raven**

raven是sentry官方针对vue推荐的插件,我们在项目中初始化，让项目链接sentry的前提，都得保证已经引入了raven-js，以及我们手动提交错误的各类方法，都由Raven提供.

### **sentry for browser**

配置应该在应用程序的生命周期中尽早发生。

完成此操作后，Sentry 的 JavaScript SDK 会捕获所有未处理的异常和事务。复制



```
import * as Sentry from "@sentry/browser";

Sentry.init({
  dsn: "https://examplePublicKey@o0.ingest.sentry.io/0",

  // Alternatively, use `process.env.npm_package_version` for a dynamic release version
  // if your build tool supports it.
  release: "my-project-name@2.3.12",
  integrations: [new Sentry.BrowserTracing()],

  // Set tracesSampleRate to 1.0 to capture 100%
  // of transactions for performance monitoring.
  // We recommend adjusting this value in production
  tracesSampleRate: 1.0,
});
```



###  **rrweb 用法**



```
// rrweb replay
https://docs.sentry.io/platforms/javascript/guides/react/configuration/integrations/rrweb/

// 1. 安装依赖
npm install --save @sentry/rrweb rrweb

// 2. 修改Sentry.init()
import SentryRRWeb from '@sentry/rrweb';
Sentry.init({
  integrations: [
    // 配置信息 https://github.com/getsentry/sentry-rrweb
    new SentryRRWeb({
      checkoutEveryNms: 10 * 1000, // 每10秒重新制作快照
      checkoutEveryNth: 200, // 每 200 个 event 重新制作快照
      maskAllInputs: false, // 将所有输入内容记录为 *
    }),
  ],
  // ...
});

// 3. 触发错误 查看 REPLAY模块

// 4. 采样 抽样决定
// 为员工捕获这些错误
const hasReplays = getCurrentUser().isStaff;
let integrations = [];
if (hasReplays) {
  console.log("[sentry] Instrumenting session with rrweb");
  integrations.push(new SentryRRWeb());
}

Sentry.init({
  dsn: "https://examplePublicKey@o0.ingest.sentry.io/0",
  integrations,
});
// 设置标签方便我们可以在查询中使用
Sentry.setTag("rrweb.active", hasReplays ? "yes" : "no");
```



### **包结构分析**

- rrweb-snapshot：包含 snapshot 和 rebuild 两个功能。 snapshot 用于将 DOM 及其状态转化为可序列化的数据结构并添加唯一标识； rebuild 则是将 snapshot 记录的数据结构重建为对应的 DOM，并插入文档中 
- rrweb：包含 record 和 replay 两个功能。 **record 用于记录 DOM 中的所有变更（mutation）,record 负责从一开始录制 DOM 全量信息，到后面监听页面的变化（mutation），并将每次的变化 emit 出来传给开发用户**； replay 则是将记录的变更按照对应的时间一一重放。 
- rrweb-player：为 rrweb 提供一套 UI 控件，提供基于图形用户界面的暂停、快进、拖拽至任意时间点播放等功能。 
- rrdom：为node平台mock浏览器的dom，event等api 

整体思路：初始化时获取当前页面的全量快照，添加监听器监听页面不同类型的变化（比如 DOM 的变化以及鼠标、滚动以及页面 resize 等的变化），当以上这些变化（mutation）发生时，根据类型的不同分别进行不同的序列化处理，并将处理好的数据 emit 出来。序列化处理时，给每个序列化的 node 节点分配一个 ID，并维护一个从 ID 到 node 节点的映射以及一个 node 节点到序列化后 serializedNode 节点的映射。

工作流程

为了实现web界面录制与回放的功能，rrweb着重实现 dom元素的 [序列化](https://link.juejin.cn/?target=https%3A%2F%2Fgithub.com%2Frrweb-io%2Frrweb%2Fblob%2Fmaster%2Fdocs%2Fserialization.md)、[增量快照](https://link.juejin.cn/?target=https%3A%2F%2Fgithub.com%2Frrweb-io%2Frrweb%2Fblob%2Fmaster%2Fdocs%2Fobserver.md)、[回放](https://link.juejin.cn/?target=https%3A%2F%2Fgithub.com%2Frrweb-io%2Frrweb%2Fblob%2Fmaster%2Fdocs%2Freplay.md) 和 [沙盒](https://link.juejin.cn/?target=https%3A%2F%2Fgithub.com%2Frrweb-io%2Frrweb%2Fblob%2Fmaster%2Fdocs%2Fsandbox.zh_CN.md) 。

Sentry-rrweb是基于rrweb的一个Sentry插件，可以将前端应用程序的记录和回放事件上传到Sentry平台，以便开发人员更好地理解和调试用户反馈的问题。以下是Sentry-rrweb使用方法的基本步骤：

1.安装和引入Sentry-rrweb插件

通过npm安装sentry-rrweb插件，并在应用程序中引入。



```
npm install @sentry/rrweb
```





```
import * as Sentry from "@sentry/browser";
import { initRrweb } from "@sentry/rrweb";

Sentry.init({
  dsn: "YOUR_DSN",
  integrations: [
    new initRrweb({
      emit: (event) => {
        // 将事件发送到Sentry平台
        Sentry.addBreadcrumb({
          category: "rrweb",
          message: JSON.stringify(event),
          level: Sentry.Severity.Info,
        });
      },
    }),
  ],
});
```



初始化Recorder

创建Recorder实例，并指定要记录的**DOM元素和配置参数**。



```
const recorder = new rrweb.Record({
  emit(event) {
    // 将事件发送到Sentry插件
    Sentry.getCurrentHub().getIntegration(initRrweb).emit(event);
  },
  checkoutEveryNth: 10, // 每10个事件检查一次是否需要停止记录
  recordCanvas: false, // 是否记录canvas元素
  recordScroll: true, // 是否记录滚动事件
  recordMutation: true, // 是否记录DOM变化事件
  recordInput: true, // 是否记录输入事件
  recordMedia: true, // 是否记录媒体事件
  hooks: {
    // 钩子函数，用于拦截和修改事件
    beforeDispatch(event) {
      console.log('before dispatch', event);
      return event;
    },
    afterDispatch(event) {
      console.log('after dispatch', event);
    },
  },
});

recorder.record(document.getElementById('app')); // 开始记录
```



回放

创建Replayer实例，并指定要回放的**事件序列和配置参数**。



```
const replayer = new rrweb.Replayer(events, {
  root: document.getElementById('app'), // 指定回放的根元素
  skipInactive: true, // 是否跳过非活动事件（例如滚动事件）
  speed: 1, // 回放速度
  showWarning: true, // 是否显示警告信息
  showDebug: true, // 是否显示调试信息
  blockClass: 'block', // 隐藏指定的CSS类
  liveMode: false, // 是否开启实时模式
  pauseAfterRound: false, // 回放一轮后是否暂停
  plugins: [], // 插件列表
});

replayer.play(); // 开始回放
```



以上是Sentry-rrweb使用方法的基本步骤，可以根据实际需求调整参数和使用插件扩展功能。注意：在使用Sentry-rrweb插件时，需要先初始化Sentry SDK，并将插件添加到integrations中。

rrweb是一个开源的Web页面录制和回放库。以下是rrweb中record方法的参数说明：



```
interface RecordOptions {
  emit?: (event: eventWithTime, isCheckout?: boolean) => void;
  checkoutEveryNth?: number;
  checkoutEveryNms?: number;
  blockClass?: string;
  ignoreClass?: string;
  maskAllInputs?: boolean;
  maskInputOptions?: {
    color?: string;
    backgroundColor?: string;
    borderRadius?: string;
    boxShadow?: string;
    zIndex?: string;
  };
  slimDOMOptions?: SlimDOMOptions;
  recordCanvas?: boolean;
  collectFonts?: boolean;
  showWarning?: boolean;
}
```



emit?: (event: eventWithTime, isCheckout?: boolean) => void：一个回调函数，用于处理每个记录的事件。eventWithTime是一个包含事件类型和时间戳的事件对象。isCheckout参数表示是否需要进行快照，如果为true，则需要进行快照，否则不需要。如果不提供此参数，则默认为false。

checkoutEveryNth?: number：指定每隔多少个事件进行一次快照。例如，如果设置为10，则每记录10个事件就会进行一次快照。如果不提供此参数，则默认为null，表示不使用此选项。

checkoutEveryNms?: number：指定每隔多少毫秒进行一次快照。例如，如果设置为1000，则每隔1秒就会进行一次快照。如果不提供此参数，则默认为null，表示不使用此选项。

blockClass?: string：指定需要屏蔽的DOM元素的类名。例如，如果设置为'block'，则所有类名为'block'的DOM元素都会被屏蔽。如果不提供此参数，则默认为'rr-block'。

ignoreClass?: string：指定需要忽略的DOM元素的类名。例如，如果设置为'ignore'，则所有类名为'ignore'的DOM元素都会被忽略。如果不提供此参数，则默认为'rr-ignore'。

maskAllInputs?: boolean：一个布尔值，表示是否需要屏蔽所有输入框。如果为true，则所有输入框都会被屏蔽。如果不提供此参数，则默认为false。

maskInputOptions?: object：一个包含屏蔽输入框选项的对象。可以指定颜色、背景色、圆角、阴影和z-index等选项。

slimDOMOptions?: SlimDOMOptions：一个包含SlimDOM选项的对象。SlimDOM是一种针对DOM树的优化方案，可以减少数据量和内存使用。可以指定要保留的DOM元素和属性等选项。

recordCanvas?: boolean：一个布尔值，表示是否需要记录canvas元素。如果为true，则所有canvas元素都会被记录。如果不提供此参数，则默认为false。

collectFonts?: boolean：一个布尔值，表示是否需要收集字体信息。如果为true，则会收集页面中使用的所有字体信息。如果不提供此参数，则默认为false。

showWarning?: boolean：一个布尔值，表示是否需要显示警告信息。如果为true，则会在控制台中显示警告信息。如果不提供此参数，则默认为false。

在rrweb中，事件对象（Event）包含了一个delay属性，用于指定该事件相对于前一个事件的延迟时间。这个属性的值是一个整数，表示该事件相对于前一个事件的时间间隔（单位是毫秒）。通常情况下，delay属性用于调整事件回放的速度，可以通过增加或减少该属性的值来控制事件之间的时间间隔。例如，将delay属性设置为1000，表示该事件与前一个事件之间的时间间隔为1秒。

在Sentry JavaScript插件中，可以通过以下方式获取事件ID和问题ID：

事件ID：在Sentry捕获异常或记录日志时，会返回一个Promise对象。可以通过该Promise对象的then()方法获取事件ID。例如：



```
Sentry.captureException(new Error('Something went wrong'))
  .then(eventId => console.log('Event ID:', eventId));
```



问题ID：在Sentry中，每个问题都有一个唯一的问题ID。可以在Sentry控制台中查看问题ID，也可以通过Sentry API获取。例如：



```
Sentry.showReportDialog({
  eventId: 'EVENT_ID',
  onSuccess: function(dialogId) {
    Sentry.API.issue(SENTRY_ISSUE_ID).then(function(issue) {
      console.log('Issue ID:', issue.id);
    });
  }
});
```



其中，eventId是事件ID，onSuccess是对话框提交成功后的回调函数，在该回调函数中可以获取问题ID。Sentry.API.issue()方法用于获取问题详情，需要传入问题ID作为参数。

//sentry怎么获取报错信息？

//首先获取对应的错误堆栈信息 通过sourcemap获取打包前的报错文件名 报错行数 列数 通过 sentry获取 在插件sdk里面完成获取

//通过git blame获取对应作者信息  在sdk里面获取  项目里面不一定支持

//git blame - L linenumber, linenumber filename.txt

/*

这个命令将会显示 filename.txt 文件中第 linenumber 行的详细信息，包括这个提交的作者、提交时间和提交信息。

需要注意的是，git blame 命令可以帮助你了解文件的变更历史，但是它并不能判断这些变更是否正确或者合理。

因此，在使用 git blame 进行代码审查或修改时，需要综合考虑多个因素，如代码质量、可读性、可维护性等。

*/

// 把对应堆栈 报错信息  行数 列数 以及文件名  作者信息存入数据库

// 在对应rrweb上传的时候 或者捕获的时候  发送请求给node服务  sendkim 把对应的开发者 对应的项目名 文件名 对应的行列号 对应的报错原因 报错时间  在kim里面进行通知

//怎么去测试

//插件引入本地 然后在璇玑里面进行抛出错误

//数据库需要加入的字段 occurTime  frame  fileName  lineNum colNum  commitUser



```
{
"event_id": "05b6a895b6e14b299a832fb9acabf367",
"project": 12345,
"timestamp": "2022-05-01T12:34:56.789Z",
"platform": "javascript",
"logger": "javascript",
"culprit": "main.js",
"message": "Uncaught TypeError: Cannot read property 'foo' of undefined",
"level": "error",
"exception": {
"values": [
{
 "type": "TypeError",
 "value": "Cannot read property 'foo' of undefined",
 "stacktrace": {
   "frames": [
     {
       "function": "getFoo",
       "filename": "http://example.com/js/main.js",
       "lineno": 123,
       "colno": 45
     },
     {
       "function": "init",
       "filename": "http://example.com/js/main.js",
       "lineno": 99,
       "colno": 12
     },
     {
       "function": "onload",
       "filename": "http://example.com/js/main.js",
       "lineno": 10,
       "colno": 34
     }
   ]
 }
}
]
},
"request": {
"url": "http://example.com/",
"headers": {},
"method": "GET"
}
}
```

##  **ECMAScript Execeptions**

[各种内建的标准错误类型](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Error)

### **Error**

基础的错误对象



```
try {
        throw new Error("错误了");
      } catch (err) {
        console.log("err.name", err.name);
        console.log("err.message", err.message);
        console.log("err.stack", err.stack);
        console.log("err.constructor:", err.constructor);
      }
```



![img](https://femarkdownpicture.oss-cn-qingdao.aliyuncs.com/imgs/out-20231229145104817.png)

### **InternalError**

出现在JavaScript引擎内部的错误,只有 firefox 支持

产生原因：过多 case 语句,正则表达式中括号过多,递归过深,内存溢出等

### **RangeError**

- 当一个值不在其允许的范围或者集合中
- 当传递一个不合法的length值作为 Array 构造器的参数创建数组
- 传递错误值到数值计算方法( Number.toExponential()，Number.toFixed(), Number.toPrecision()等）

### **ReferenceError**

一个不存在的变量被引用时发生的错误

当代码中存在引用未定义变量或函数时，JavaScript 引擎就会抛出 ReferenceError 错误。这通常发生在以下几种情况：

**变量或函数名未定义**：例如，当尝试使用一个没有声明过的变量时，就会抛出 ReferenceError 错误。



```
console.log(a); // ReferenceError: a is not defined
```



**对象属性未定义**：例如，当尝试访问一个未定义的对象属性时，就会抛出 ReferenceError 错误。



```
var obj = {};
console.log(obj.foo); // ReferenceError: obj.foo is not defined
```



**使用 delete 操作符删除不存在的属性**：例如，当尝试删除一个对象中不存在的属性时，就会抛出 ReferenceError 错误。



```
var obj = {};
delete obj.foo; // ReferenceError: obj.foo is not defined
```



在 JavaScript 中，ReferenceError 错误通常是由编程错误引起的，例如拼写错误、变量声明的位置错误等。

### **SyntaxError**

- 解析语法上不合法的代码的错误
- 不能被用户代码catch的SyntaXError

当代码中存在语法错误时，JavaScript 引擎就会抛出 SyntaxError 错误。

**语法错误：**例如，当代码中存在括号不匹配、语句不完整、操作符使用错误等语法错误时，就会抛出 SyntaxError 错误。



```
console.log(1; // SyntaxError: missing ) after argument list
```



**非法字符：**例如，当代码中存在非法字符时，就会抛出 SyntaxError 错误。



```
console.log('hello'》); // SyntaxError: Invalid or unexpected token
```



**非法转义字符：**例如，当代码中存在非法的转义字符时，就会抛出 SyntaxError 错误。



```
console.log('hello\''); // SyntaxError: unterminated string literal
```



### **TypeError**

当在代码中使用了不支持的操作或类型时，JavaScript 引擎就会抛出 TypeError 错误

1. **尝试访问未定义或空对象的属性或方法。**

访问未定义或空对象的属性或方法时，会产生TypeError。例如：



```
let person = {};
console.log(person.name); // 输出 "undefined"
console.log(person.name.length); // TypeError: Cannot read property 'length' of undefined
```



1. 尝试调用非函数类型的变量或属性。



```
let message = "Hello, world!";
console.log(message()); // TypeError: message is not a function
```



1. 尝试对非数组或类数组对象执行数组操作，如push、pop等。



```
let name = "John";
name.push("Doe"); // TypeError: name.push is not a function
```



1. 尝试使用未声明的变量或属性。



```
console.log(age); // ReferenceError: age is not defined
console.log(user.age); // TypeError: Cannot read property 'age' of undefined
```



1. 尝试使用不支持的类型进行操作，如使用null或undefined进行算术操作。



```
let person = null;
let age = 30;
console.log(age/person); // TypeError: Cannot convert object to primitive value
```



值的类型非预期类型时发生的错误



```
undefined.abc
null.abc
new 123()
"1" in "123"
const a = 1
a = 2
```



**错误关键词**



```
Cannot read property of undefined
Cannot read properties of  
is not a constructor
Assignment to constant variable.
```



### **URIError**

当使用不合法的 URL 或 URI 参数时，JavaScript 引擎就会抛出 URIError 错误。

**在 URI 中包含非法字符：**例如，当我们使用不合法的字符（如空格、#、%等）作为 URI 参数时，就会抛出 URIError 错误。



```
let url = 'https://www.example.com/search?q=how to use javascript#basics';
let encodedUrl = encodeURI(url);
console.log(encodedUrl); // https://www.example.com/search?q=how%20to%20use%20javascript#basics
```



**在字符串转换为 URI 时遇到错误：**例如，当我们尝试使用 encodeURI() 或 decodeURI() 方法转换不合法的字符串时，就会抛出 URIError 错误。



```
let url = 'https://www.example.com/search?q=how to use javascript#basics';
let encodedUrl = encodeURI(url);
let decodedUrl = decodeURIComponent(encodedUrl); // URIError: malformed URI sequence
```



URIError 错误通常是由于使用不合法的 URL 或 URI 参数或字符编码错误引起的。应该使用 URL 和 URI 相关的 JavaScript 方法，如 encodeURI()、encodeURIComponent()、decodeURI() 和 decodeURIComponent() 来正确处理 URL 和 URI，以避免出现这类错误。

### **AggregateError**

它是在多个操作中发生错误时将多个错误合并成一个单独的错误对象。AggregateError 错误对象包含一个数组，其中每个元素都是一个单独的错误对象。这个错误类型可以用于异步操作中，以便将多个操作的错误报告给用户。

在使用 Promise.all() 或 Promise.allSettled() 方法时，如果其中一个 Promise 对象发生错误，那么 Promise.all() 或 Promise.allSettled() 方法就会返回一个 AggregateError 类型的错误对象。这个错误对象包含了所有发生错误的 Promise 对象的错误信息。



```
const promise1 = Promise.resolve(1);
const promise2 = Promise.reject(new Error('Error 1'));
const promise3 = Promise.reject(new Error('Error 2'));

Promise.all([promise1, promise2, promise3])
  .then(values => console.log(values))
  .catch(error => {
    if (error instanceof AggregateError) {
      console.log(error.errors); // [Error: Error 1, Error: Error 2]
    }
});
```



在处理多个异步操作时，AggregateError 错误类型可以帮助我们更好地捕获和处理所有发生的错误信息。

## **DOMException**

[**DOMException**](https://developer.mozilla.org/zh-CN/docs/Web/API/DOMException#Error_names)接口代表调用方法或访问 Web API 属性时发生的异常事件（被称为**异常**，**exception**）**用于表示在操作 DOM 树时可能发生的错误**

在标准的 DOM API 中，DOMException 对象通常不包含堆栈跟踪信息。这是因为 DOMException 是在底层的浏览器引擎中抛出的，而不是在 JavaScript 的执行上下文中。

在捕获 DOMException 时获取堆栈跟踪信息，可以使用标准的 JavaScript 异常处理机制。通过使用 try...catch 语句来捕获 DOMException，并使用 console.trace() 或 console.error() 打印堆栈跟踪信息。

DOMException.message 

返回一个 DOMString 代表与给定的错误名称有关信息或描述。

DOMException.name 

返回一个 DOMString 包含与错误名称相关的字符串

IndexSizeError：索引大小错误，表示给定的索引值超出了允许的范围。

HierarchyRequestError：层次请求错误，表示节点在 DOM 树中的位置不允许执行请求的操作。

WrongDocumentError：错误的文档错误，表示节点和操作不属于同一个文档。

InvalidCharacterError：无效字符错误，表示字符串中包含无效的字符。

NoModificationAllowedError：不允许修改错误，表示对只读或不允许修改的对象进行了修改操作。

NotFoundError：未找到错误，表示未找到请求的节点或对象。

NotSupportedError：不支持错误，表示请求的操作不受当前环境或对象的支持。

InvalidStateError：无效状态错误，表示对象处于无效或不允许执行请求操作的状态。

SyntaxError：语法错误，表示传递给方法或函数的参数具有无效的语法。

InvalidModificationError：无效修改错误，表示对对象进行了无效的修改操作。

NamespaceError：命名空间错误，表示操作涉及无效的命名空间。

InvalidAccessError：无效访问错误，表示对对象的访问无效或被拒绝。

TypeMismatchError：类型不匹配错误，表示传递给方法或函数的参数的类型不匹配。

SecurityError： 安全错误，表示操作被安全限制或违反了安全策略。

**NetworkError：** 发生网络错误。通常在使用 Fetch API 或 XMLHttpRequest 进行网络请求时发生

**AbortError**： 操作被中止。   通常为主动中断或者再请求时进行页面导航

URLMismatchError： 给定的URL不匹配另一个URL。

QuotaExceededError：给定配额已经超过了。

TimeoutError： 操作超时。

InvalidNodeTypeError： 这个操作的节点是不正确的或祖先是不正确的。

DataCloneError： 对象不能克隆。

## **Axios的createError**

`createError` 是 `axios` 库中的一个函数，用于创建一个 `Error` 对象。

在 `axios` 库中，当发生错误时，会调用 `createError` 函数来创建一个错误对象，然后将这个错误对象作为 Promise 的拒绝值返回给调用方。

`createError` 函数的定义如下：



```
function createError(message, config, code, request, response) {
  const error = new Error(message);
  return enhanceError(error, config, code, request, response);
}
```



它接受五个参数：

- `message`：错误信息。
- `config`：请求配置对象。
- `code`：HTTP 状态码。
- `request`：XMLHttpRequest 对象的实例。
- `response`：响应对象。

`createError` 函数首先创建一个普通的 `Error` 对象，并将 `message` 作为参数传入。然后，它调用 `enhanceError` 函数，将创建的 `Error` 对象和其他参数一起传入，以创建一个更完整的错误对象，最终将这个错误对象返回。

`enhanceError` 函数的作用是将传入的参数添加到错误对象的属性中，然后返回这个错误对象。由于 `createError` 函数返回的是 `enhanceError` 函数的返回值，因此最终返回的是一个多了一些属性的错误对象，这个错误对象包含了详细的错误信息，以及一些请求和响应的相关信息。

enhanceError 方法就是单纯为了升级 Error 对象，给 Axios 生成的错误对象添加 config、code、request 和 response 属性



```
function enhanceError(error, config, code, request, response) {
  error.config = config;
  if (code) {
    error.code = code;
  }
  error.request = request;
  error.response = response;
  error.isAxiosError = true;

  // 添加其他自定义属性或方法

  return error;
}
```



## **Throw**

用于抛出异常并停止代码执行。当代码运行到一个 throw 语句时，程序会停止执行并抛出一个异常对象。如果没有被处理，**这个异常对象会向上冒泡到调用栈的上一级，并继续向上直到被处理或者到达全局作用域，此时会导致程序崩溃。**

## **错误捕获**

### **脚本错误**

**脚本错误参数对象** instanceof ErrorEvent

**脚本错误的捕获方式有：**

try catch：通过try...catch我们能够知道出错的信息,并且也有堆栈信息可以知道在哪个文件第几行第几列发生错误。只能捕获同步代码的异常，需要await进行转化

window.onerror：能全局捕获错误，可以拿到出错的信息以及文件名、行号、列号等信息；能捕获即时运行错误，不能捕获资源加载错误

### **资源加载错误**

**资源加载错误包括：img、script、link、audio、video、iframe**

资源加载错误没有message，资源错误的参数对象 instanceof Event

捕获方式：

object.onerror：如：img标签、script标签都可以添加onerror事件，用来捕获资源加载错误

### **Promise错误**

try catch和window.onerror是无法捕捉Promise错误的（因为是异步）

而当 Promise 被 reject 且没有 reject 处理器的时候，会触发 unhandledrejection 事件

当 Promise 被 reject 且有 reject 处理器的时候，会触发 rejectionhandled 事件。

说明：Sentry这边只收集没有被reject的错误即window.unhandledrejection

### **异常传播和处理**

JS 中异常传播是自动的，不需要程序员手动地一层层传递。如果一个异常没有被 catch，它会沿着函数调用栈一层层传播直到栈空。

**throw（抛出异常）** 和 **catch（处理异常）**。 当一个异常被抛出的时候，异常的传播就开始了。异常会不断传播直到遇到第一个 catch。 如果程序员没有手动 catch，那么一般而言程序会抛出类似**unCaughtError**，表示发生了一个异常，并且这个异常没有被程序中的任何 catch 语言处理。未被捕获的异常通常会被打印在控制台上，里面有详细的堆栈信息，从而帮助程序员快速排查问题。实际上我们的程序的目标是**避免 unCaughtError**这种异常，而不是一般性的异常。

JS 的 Error 对象没有 code 属性，只能根据 message 来呈现



```
function a() {
  b();
}
function b() {
  c();
}
function c() {
  throw new Error("an error  occured");
}
a();
```



![img](https://femarkdownpicture.oss-cn-qingdao.aliyuncs.com/imgs/out-20231229145105671.png)

没有 catch 错误，因此上面才会有**uncaught Error,并且为错误输出**



```
function a() {
  b();
}
function b() {
  c();
}
function c() {
  try {
    throw new Error("an error  occured");
  } catch (err) {
    console.log(err);
  }
}
a();
```



![img](https://femarkdownpicture.oss-cn-qingdao.aliyuncs.com/imgs/out-20231229145106192.png)

没有**uncaught Error**

## **Sentry对错误信息的处理**

针对事件处理sentry内部主要是使用了_installGlobalOnErrorHandler

和_installGlobalOnUnhandledRejectionHandler

_installGlobalOnErrorHandler对event处理



```
          const event = isPrimitive(error)
            ? this._eventFromIncompleteOnError(...)
            : this._enhanceEventWithInitialFrame(
                eventFromUnknownInput(...))
```



_installGlobalOnUnhandledRejectionHandler



```
          const event = isPrimitive(error)
            ? this._eventFromRejectionWithPrimitive(...)
            : eventFromUnknownInput(...);
```



通过isPrimitive去判断错误类型是基本类型还是引用类型而走不同的操作

### **eventFromUnknownInput**



```
eventFromUnknownInput(error, undefined, {
  attachStacktrace: client && client.getOptions().attachStacktrace,
  rejection: false,
}) 
 // exception为错误信息，options是用户在Sentry.init中设置的attachStacktrace
function eventFromUnknownInput(
  exception: unknown,
  syntheticException?: Error,
  attachStacktrace?: boolean,
  isUnhandledRejection?: boolean,
): Event {
  let event: Event;

  if (isErrorEvent(exception as ErrorEvent) && (exception as ErrorEvent).error) {
    // If it is an ErrorEvent with `error` property, extract it to get actual Error
    const errorEvent = exception as ErrorEvent;
    return eventFromError(errorEvent.error as Error);
  }

  // If it is a `DOMError` (which is a legacy API, but still supported in some browsers) then we just extract the name
  // and message, as it doesn't provide anything else. According to the spec, all `DOMExceptions` should also be
  // `Error`s, but that's not the case in IE11, so in that case we treat it the same as we do a `DOMError`.
  //
  // https://developer.mozilla.org/en-US/docs/Web/API/DOMError
  // https://developer.mozilla.org/en-US/docs/Web/API/DOMException
  // https://webidl.spec.whatwg.org/#es-DOMException-specialness
  if (isDOMError(exception as DOMError) || isDOMException(exception as DOMException)) {
    const domException = exception as DOMException;

    if ('stack' in (exception as Error)) {
      event = eventFromError(exception as Error);
    } else {
      const name = domException.name || (isDOMError(domException) ? 'DOMError' : 'DOMException');
      const message = domException.message ? `${name}: ${domException.message}` : name;
      event = eventFromString(message, syntheticException, attachStacktrace);
      addExceptionTypeValue(event, message);
    }
    if ('code' in domException) {
      event.tags = { ...event.tags, 'DOMException.code': `${domException.code}` };
    }

    return event;
  }
  if (isError(exception)) {
    // we have a real Error object, do nothing
    return eventFromError(exception);
  }
  if (isPlainObject(exception) || isEvent(exception)) {
    // If it's a plain object or an instance of `Event` (the built-in JS kind, not this SDK's `Event` type), serialize
    // it manually. This will allow us to group events based on top-level keys which is much better than creating a new
    // group on any key/value change.
    const objectException = exception as Record<string, unknown>;
    event = eventFromPlainObject(objectException, syntheticException, isUnhandledRejection);
    addExceptionMechanism(event, {
      synthetic: true,
    });
    return event;
  }

  // If none of previous checks were valid, then it means that it's not:
  // - an instance of DOMError
  // - an instance of DOMException
  // - an instance of Event
  // - an instance of Error
  // - a valid ErrorEvent (one with an error property)
  // - a plain Object
  //
  // So bail out and capture it as a simple message:
  event = eventFromString(exception as string, syntheticException, attachStacktrace);
  addExceptionTypeValue(event, `${exception}`, undefined);
  addExceptionMechanism(event, {
    synthetic: true,
  });

  return event;
}
```



isErrorEvent



```
 错误类型是ErrorEvent，包含比较详细的错误信息
function isErrorEvent(wat) {
    return Object.prototype.toString.call(wat) === '[object ErrorEvent]';
  }
```



isDOMError  isDOMException



```
  function isDOMError(wat) {
    return Object.prototype.toString.call(wat) === '[object DOMError]';
  }
  
   function isDOMException(wat) {
    return Object.prototype.toString.call(wat) === '[object DOMException]';
  }
```



isError 



```
  function isError(wat) {
    switch (Object.prototype.toString.call(wat)) {
      case '[object Error]':
        return true;
      case '[object Exception]':
        return true;
      case '[object DOMException]':
        return true;
      default:
        return isInstanceOf(wat, Error);
    }
  }
```



isPlainObject或者isEvent针对普通消息



```
  function isEvent(wat) {
    return typeof Event !== 'undefined' && isInstanceOf(wat, Event);
  }

  function isPlainObject(wat) {
    return Object.prototype.toString.call(wat) === '[object Object]';
  }
```



处理eventFromStacktrace，eventFromPlainObject，eventFromString 都是拿到错误消息进行更进一步的数据处理。

### **computeStackTrace 获取错误堆栈**

computeStackTrace主要获取当前的错误堆栈

把stack进行split转换数组，然后根据浏览器信息做不同处理，

最后返回stack是带有args，line，func，url的数据格式



```
args: []
column: 9
func: "externalLibrary"
line: 2
url: ""
```



##### **eventFromStacktrace、eventFromString和 eventFromPlainObject**

拿到错误堆栈等信息进行进一步处理



```
  function eventFromStacktrace(stacktrace) {
    const exception = exceptionFromStacktrace(stacktrace);
    return {
      exception: {
        values: [exception],
      },
    };
  }
--------------------------------------------------------------------------------------------
  function eventFromString(input, syntheticException, options = {}) 	{
    const event = {
      message: input,
    };
    if (options.attachStacktrace && syntheticException) {
      const stacktrace = computeStackTrace(syntheticException);
      const frames = prepareFramesForEvent(stacktrace.stack);
      event.stacktrace = {
        frames,
      };
    }
    return event;
  }
-------------------------------------------------------------------------------------------
function eventFromPlainObject(exception, syntheticException, rejection) {
    const event = {
      exception: {
        values: [
          {
            type: isEvent(exception) ? exception.constructor.name : rejection ? 'UnhandledRejection' : 'Error',
            value: `Non-Error ${
              rejection ? 'promise rejection' : 'exception'
            } captured with keys: ${extractExceptionKeysForMessage(exception)}`,
          },
        ],
      },
      extra: {
        __serialized__: normalizeToSize(exception),
      },
    };
    if (syntheticException) {
      const stacktrace = computeStackTrace(syntheticException);
      const frames = prepareFramesForEvent(stacktrace.stack);
      event.stacktrace = {
        frames,
      };
    }
    return event;
  }
```



最终返回的数据



```
  exception:  {
      stacktrace: [
        {
          colno: 1,
          filename:
          'https://',
          function: '?',
          in_app: true,
          lineno: 5,
        },
        {
          colno: 9,
          filename:
            'https://',
          function: 'externalLibrary',
          in_app: true,
          lineno: 2,
        },
      ];
      type: 'Error';
      value: 'externalLibrary method broken';
    }
```



错误消息的类型去走eventFromStacktrace、eventFromString和 eventFromPlainObject其中的一个方法。**像错误类型为DOMError、DOMException、普通对象的此时是没有错误堆栈的消息的**，而其他的会通过computeStackTrace去抹平不同浏览器的差异，获取错误堆栈，最后对错误数据处理返回统一的结构。

对window.onerror和window.unhandledrejection进行劫持

| 错误类型                     | 捕获方式                                     | 处理函数                           | 详情                     |
| ---------------------------- | -------------------------------------------- | ---------------------------------- | ------------------------ |
| throw '错误测试'             | window.onerror 的 错误类型是基本类型         |                                    | 有错误栈信息             |
| throw new Error(' 错误测试') | window.onerror 的 错误类型是引用类型         | eventFromPlainObject()             | 有错误栈消息             |
|                              | window.error 不上报错误                      |                                    | 不进行错误报没有错误信息 |
| reject('错误测试')           | window.unhandledrejection 错误类型是基本类型 | _eventFromRejectionWithPrimitive() | 没有错误栈信息           |
| reject(obj)                  | window.unhandledrejection 错误类型是引用类型 | eventFromPlainObject()             | 没有错误栈信息           |
|                              | 引用类型并且是DOMException                   | eventFromUnknownInput()            | 没有错误栈信息           |

## **提取分析错误**

按照项目来区分，璇玑系统，时间最近一个月，

### **1.查询接口**

区分为2大类：所有错误  、可回溯定位错误

 需要查询分析的：错误类型（按照js的错误类型区分），错误源分类 ，错误模块，错误时间（按照周）

错误类型：按照errorMessage或者errorType进行字符判断，然后计入

错误源分类：按照sourcepath 进行判断 可回溯的 还有具体是哪报错了

错误模块：错误的路径分析，通过路径确定是那个业务模块下的代码

错误时间：按照发生时间进行计算数量分析

### **2.展示页面**

错误类型，饼图展示最近一个月的各种错误的占比和数量  有类型和数量

错误源分类，饼图分析最近一个月的错误源分类（业务代码，npm包，浏览器兼容性，模版错误）

错误模块，饼图展示各个业务模块的占比   

错误时间，做一个饼图占比或者按时间的条形图



```
AxiosError	
CanceledError	
Error	
IndexSizeError	
InvalidStateError	
NavigationDuplicated	
NotAllowedError	
NotFoundError	
NotSupportedError	
RangeError	
ReferenceError	
SyntaxError	
TypeError	
URIError
```





```
AxiosError	71	
CanceledError	20929	
Error	18981	
IndexSizeError	8	
InvalidStateError	3	
NavigationDuplicated	58	
NotAllowedError	9	
NotFoundError	3	
NotSupportedError	208	
RangeError	14	
ReferenceError	2	
SyntaxError	196	
TypeError	4643	
URIError  15
```

Todos:

1.错误原因分析

通过字段进行更详细的分析  **DOMException  浏览器版本问题**  

**es6的api基本都支持**

**es7**

**es 10以上api需要考虑一下**

ECMAScript 2019（也称为 ES10 或 ES2019）引入了一些新的 JavaScript API。以下是其中的一些：

Array.prototype.flat() 和 Array.prototype.flatMap(): 这两个方法用于处理嵌套数组。flat() 方法将嵌套数组展平为一个新数组，而 flatMap() 方法在展平数组的同时，还可以对每个元素进行映射和操作。

Object.fromEntries(): 这个静态方法将键值对数组转换为对象。它接受一个键值对数组（如 [[key1, value1], [key2, value2]]）作为参数，并返回一个由这些键值对组成的新对象。

String.prototype.trimStart() 和 String.prototype.trimEnd(): 这两个方法用于去除字符串开头或结尾的空格字符。trimStart() 方法去除开头的空格，trimEnd() 方法去除结尾的空格。

Symbol.prototype.description: 这个属性用于获取 Symbol 对象的描述字符串。它返回一个可读的字符串，表示 Symbol 的描述信息。

ECMAScript 2020（也称为 ES11 或 ES2020）引入了一些新的 JavaScript API。以下是其中的一些：

BigInt: BigInt 是一种新的原始数据类型，用于表示任意精度的整数。它允许处理超过 Number 数据类型所能表示的范围的整数。

Promise.allSettled(): 这个静态方法接受一个 Promise 数组，并返回一个新的 Promise，该 Promise 在所有输入 Promise 完成（无论是成功还是失败）后解析。与 Promise.all() 不同，Promise.allSettled() 不会在任何一个 Promise 失败时立即拒绝。

String.prototype.matchAll(): 这个方法返回一个包含所有匹配正则表达式的迭代器对象。您可以使用它来遍历一个字符串中所有匹配的结果。

globalThis: 这是一个全局对象的新属性，可以在任何环境中访问全局对象，无论是在浏览器中还是在 Node.js 环境中。

ECMAScript 2021（也称为 ES12 或 ES2021）引入了一些新的 JavaScript API。以下是其中的一些：

String.prototype.replaceAll(): 这个方法接受两个参数，用于将字符串中的所有匹配项替换为指定的新字符串。与 replace() 方法不同，replaceAll() 替换所有匹配项，而不仅仅是第一个匹配项。

Promise.any(): 这个静态方法接受一个 Promise 数组，并返回一个新的 Promise，该 Promise 在输入 Promise 数组中的任何一个 Promise 完成（即解决或拒绝）时解析。与 Promise.race() 方法不同，Promise.any() 只要有一个 Promise 完成就解析，而不是第一个完成的 Promise。

WeakRef 和 FinalizationRegistry: 这两个 API 是用于处理弱引用的。WeakRef 对象允许创建对对象的弱引用，而 FinalizationRegistry 对象允许在对象被垃圾回收时执行清理操作。

Logical Assignment Operators: 这些是逻辑赋值运算符，包括 ||=、&&= 和 ??=。它们允许在进行逻辑运算的同时进行赋值操作，简化了一些常见的编程模式。

正则零宽断言低版本safari浏览器报错



```
SyntaxError: Invalid regular expression: invalid group specifier name
```



**意思就是，正则表达式无效：组说明符名称无效。**

什么是零宽断言？

用于查找在某些内容(但并不包括这些内容)之前或之后的东西，也就是说它们像\b,^,$那样用于指定一个位置，这个位置应该满足一定的条件(即断言)，因此它们也被称为零宽断言。最好还是拿例子来说明吧： 断言用来声明一个应该为真的事实。正则表达式中只有当断言为真时才会继续进行匹配。

正则零宽断言，一共4种 1、(?=xxx) 例：\b\w+(?=ing\b)，匹配以ing结尾的单词的前面部分 2、(?<=xxx) 例：(?<=\bre)\w+\b会匹配以re开头的单词的后半部分 3、(?!xxx) 例：\d{3}(?!\d)匹配三位数字，而且这三位数字的后面不能是数字 4、(?<!xxx) 例：(?<![a-z])\d{7}匹配前面不是小写字母的七位数字

![img](https://docs.corp.kuaishou.com/image/api/external/load/out?code=fcAC6Q4hC1fDITvyf2nUK_1pB:-5164182880490647560fcAC6Q4hC1fDITvyf2nUK_1pB:1703834444256)

https://blog.csdn.net/xiamocsdn/article/details/125221297

[**https://caniuse.com/**](https://caniuse.com/)

  

雷达关于浏览器兼容性的

2.错误分析维度
